version: "2"
linters:
  settings:
    copyloopvar:
      # Check all assigning the loop variable to another variable.
      # Default: false
      check-alias: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - gosec
    - importas
    - inamedparam
    - misspell
    - musttag
    - nilerr
    - prealloc
    - predeclared
    - protogetter
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
    - copyloopvar
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - data$
      - .helm$
      - bin$
      - conf$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
